; ==================================================================================================
; Title:   SmplPlot.inc
; Author:  Héctor S. Enrique - January 2026
; Version: 1.0.0
; Purpose: Simple graphic implementation 
; Notes:    Framework version C.2.0, 2026
;               - First release.
; ==================================================================================================

% include SmplPlot_OOP.inc

if IMPLEMENT

 % include SmplPlot_PROC.inc    

 % include SerieGraph.inc    

endif
