; ==================================================================================================
; Title:   FOMSI.inc
; Author:  Héctor S. Enrique - January 2026
; Version: 1.0.0
; Purpose: FOMSI Model implementation 
; Notes:    Framework version C.2.0, 2026
;               - First release.
; ==================================================================================================

include FOMSI_OOP.inc
if IMPLEMENT
       
    include FOMSI_PROC.inc
endif